version: "3.8"
services:
    pydataq01:
        container_name: pydataq01
        image: "postgres"
        ports:
            - "5432:5432"
        volumes: 
            - ./pydataq01:/var/lib/postgresql/data
            - ../sample_dataset/dataset.sql:/docker-entrypoint-initdb.d/init.sql
        environment: 
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    pydataq02:
        container_name: pydataq02
        image: "postgres"
        ports:
            - "5433:5432"
        volumes: 
            - ./pydataq02:/var/lib/postgresql/data
            - ../sample_dataset/dataset.sql:/docker-entrypoint-initdb.d/init.sql
        environment: 
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    pgAdmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        ports:
            - 9999:80
        volumes: 
            - ./pgadmin:/var/lib/pgadmin/data
            - ../sample_dataset/dataset.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - PGADMIN_DEFAULT_EMAIL=pydataq@pydataq.com
            - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}